/* Constants for API and database data */

module.exports = {
	USER_USERNAME_MIN: 3,
	USER_USERNAME_MAX: 24,
	USER_PASSWORD_MIN: 3,
	USER_PASSWORD_MAX: 64,
	USER_EMAIL_MIN: 3,
	USER_EMAIL_MAX: 320,
	USER_NAME_MAX: 16,
	USER_BIO_MAX: 255,
	USER_TOKEN_MAX: 128,

	GROUP_CODE_MAX: 16,
	GROUP_NAME_MAX: 24,

	MESSAGE_MESSAGE_MAX: 255,
}